name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push: { branches: [master] }

jobs:
  hoge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: sh .github/workflows/search.sh
